#prometheus:
#  config:
#    scrape_configs:
#      - job_name: "app-metrics"
#        kubernetes_sd_configs:
#          - role: pod
#        relabel_configs:
#          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
#            action: keep
#            regex: "true"
#          - source_labels: [__meta_kubernetes_pod_ip]
#            target_label: __address__
#            replacement: "$1:8080"
