namespace: observability
name: invoiced

replicas: 3
serviceAccountName: otelcontribcol
image: otel/opentelemetry-collector-contrib:0.140.1
featureGates:
  - "--feature-gates=filelog.allowHeaderMetadataParsing"
  - "--feature-gates=service.profilesSupport"
  - "--feature-gates=transform.flatten.logs"
resources:
  limits:
    cpu: 200m
    memory: 500Mi
  requests:
    cpu: 200m
    memory: 500Mi

labels:
  app: opentelemetry
  component: otel-collector

# RÃ©pertoires contenant les fragments YAML
receiversDir: "files/default/receivers"
processorsDir: "files/default/processors"
exportersDir: "files/default/exporters"
connectorsDir: "files/default/connectors"
pipelinesFile: "files/default/pipelines.yaml"
agentPipelinesFile: "files/default/agent-pipelines.yaml"
