apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-collector
  namespace: {{ .Values.namespace }}
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
spec:
  selector:
    {{- toYaml .Values.labels | nindent 4 }}
  ports:
    - name: otlp
      port: 4317
      targetPort: 4317  # ‚Üê Ajoutez targetPort
    - name: http
      port: 4318
      targetPort: 4318
    - name: metrics
      port: 8000
      targetPort: 8000
